import os
import re
import uuid
from flask import Flask, request, jsonify, session
from flask_cors import CORS
from dotenv import load_dotenv

# Optional AI import
try:
    from openai import OpenAI
except ImportError:
    OpenAI = None

load_dotenv()

app = Flask(__name__)
app.secret_key = os.getenv('SESSION_SECRET', 'dev-secret-key-change-this')
CORS(app, origins=['http://localhost:3000', 'http://127.0.0.1:3000'], supports_credentials=True)

# ============================================================
# 1. In‑memory store (session‑scoped)
# ============================================================
store = {}  # key: session_id, value: {'memories': {}, 'workflow': None}

def get_store(sid):
    if sid not in store:
        store[sid] = {'memories': {}, 'workflow': None}
    return store[sid]

def save_memory(sid, key, value):
    data = get_store(sid)
    data['memories'][key] = value

def get_memory(sid, key):
    data = get_store(sid)
    return data['memories'].get(key)

def get_all_memories(sid):
    data = get_store(sid)
    return data['memories'].copy()

def set_workflow(sid, workflow_state):
    data = get_store(sid)
    data['workflow'] = workflow_state

def get_workflow(sid):
    data = get_store(sid)
    return data['workflow']

def clear_workflow(sid):
    data = get_store(sid)
    data['workflow'] = None

# ============================================================
# 2. Workflow definitions & service
# ============================================================
WORKFLOWS = {
    'DAILY_DIG': {
        'name': 'Daily Dig',
        'steps': [
            {'id': 'objective', 'prompt': 'What is your main objective for today?'},
            {'id': 'obstacle', 'prompt': 'What obstacle stands in your way?'},
            {'id': 'seed', 'prompt': None}  # generated by AI
        ]
    },
    'REFLECTION': {
        'name': 'Reflection',
        'steps': [
            {'id': 'challenge', 'prompt': 'Tell me about a recent challenge you faced.'},
            {'id': 'sunlight', 'prompt': 'What sunlight (positive aspect) came from that challenge?'},
            {'id': 'growth', 'prompt': None}
        ]
    }
}

def start_workflow(sid, wf_type):
    if wf_type not in WORKFLOWS:
        return None
    state = {
        'type': wf_type,
        'step_index': 0,
        'answers': {},
        'is_active': True
    }
    set_workflow(sid, state)
    return WORKFLOWS[wf_type]['steps'][0]['prompt']

def advance_workflow(sid, user_message):
    state = get_workflow(sid)
    if not state or not state['is_active']:
        return None

    wf = WORKFLOWS[state['type']]
    step_idx = state['step_index']
    step = wf['steps'][step_idx]

    # Save answer
    state['answers'][step['id']] = user_message
    state['step_index'] += 1

    # Check if workflow is complete (we have all except the final AI‑generated step)
    if state['step_index'] >= len(wf['steps']) - 1:
        state['is_active'] = False
        set_workflow(sid, state)
        # store answers
        save_memory(sid, f"workflow_{state['type'].lower()}", state['answers'])
        for k, v in state['answers'].items():
            save_memory(sid, k, v)
        return {'done': True, 'answers': state['answers'], 'type': state['type']}
    else:
        next_step = wf['steps'][state['step_index']]
        set_workflow(sid, state)
        return {'done': False, 'prompt': next_step['prompt'], 'step': next_step['id']}

def is_workflow_active(sid):
    state = get_workflow(sid)
    return state is not None and state.get('is_active', False)

def get_current_prompt(sid):
    state = get_workflow(sid)
    if not state or not state['is_active']:
        return None
    wf = WORKFLOWS[state['type']]
    step = wf['steps'][state['step_index']]
    return step['prompt']

def generate_workflow_summary(wf_type, answers):
    if wf_type == 'DAILY_DIG':
        return (f"🌱 Today's Dig complete! Objective: \"{answers.get('objective', '')}\". "
                f"Obstacle: \"{answers.get('obstacle', '')}\". Now planting your seed...")
    elif wf_type == 'REFLECTION':
        return (f"🌿 Reflection complete. Challenge: \"{answers.get('challenge', '')}\". "
                f"Sunlight: \"{answers.get('sunlight', '')}\". Growing your insight...")
    return "Workflow complete."

# ============================================================
# 3. AI Service (mock + optional OpenAI)
# ============================================================
class MockAI:
    def generate_response(self, user_message, memories, workflow_context):
        mem_str = '. '.join([f"{k}: {v}" for k, v in memories.items()]) or 'No memories yet.'
        reply = f"🌳 The Arboreal Sage remembers: {mem_str}. "
        if workflow_context:
            reply += f"You are in the middle of a \"{workflow_context.get('type')}\" workflow. "
            reply += f"Please answer: {workflow_context.get('prompt')}"
        else:
            reply += f"You asked: \"{user_message}\". "
            reply += "Let’s explore that with the patience of a growing tree. "
            reply += "Would you like to start a Daily Dig or a Reflection session?"
        return reply

class OpenAIService:
    def __init__(self):
        self.client = OpenAI(api_key=os.getenv('OPENAI_API_KEY')) if OpenAI else None

    def generate_response(self, user_message, memories, workflow_context):
        if not self.client:
            return MockAI().generate_response(user_message, memories, workflow_context)

        mem_str = '. '.join([f"{k}: {v}" for k, v in memories.items()]) or 'None yet.'
        system = (
            "You are The Arboreal Sage – a calm, wise, nature-inspired guide. "
            "Use metaphors about trees, seasons, and growth. Respond concisely, with empathy. "
            "Avoid jargon. Keep responses to 2-3 short paragraphs. "
            f"Known memories about the user: {mem_str}"
        )
        user_prompt = user_message
        if workflow_context:
            system += f" The user is currently in a \"{workflow_context.get('type')}\" workflow. Guide them to answer the current question without skipping ahead."
            user_prompt = f"[Workflow: {workflow_context.get('type')}] User says: {user_message}"

        try:
            completion = self.client.chat.completions.create(
                model='gpt-4o-mini',
                messages=[
                    {'role': 'system', 'content': system},
                    {'role': 'user', 'content': user_prompt}
                ],
                temperature=0.7,
                max_tokens=300
            )
            return completion.choices[0].message.content
        except Exception as e:
            print("OpenAI error:", e)
            return MockAI().generate_response(user_message, memories, workflow_context)

# Choose service
if os.getenv('OPENAI_API_KEY'):
    ai_service = OpenAIService()
else:
    ai_service = MockAI()
    print("⚠️ No OPENAI_API_KEY set. Using mock AI responses.")

# ============================================================
# 4. Intent detection helpers
# ============================================================
def detect_workflow_intent(text):
    t = text.lower()
    if re.search(r'(daily dig|plan my day|set.*objective|today\'?s? (goal|plan))', t):
        return 'DAILY_DIG'
    if re.search(r'(reflect|journal|reflection|process.*challenge)', t):
        return 'REFLECTION'
    return None

def is_memory_check(text):
    t = text.lower()
    return re.search(r'(how did .* go|check.*progress|my (root|objective)|last time|previous (goal|session)|root take root|check on my root)', t) is not None

def is_name_intro(text):
    match = re.search(r'my name is\s+([\w\s]+)', text, re.I)
    if match:
        return match.group(1).strip()
    return None

# ============================================================
# 5. Main API route
# ============================================================
@app.route('/api/chat', methods=['POST'])
def chat():
    data = request.get_json()
    user_message = data.get('message', '').strip()
    if not user_message:
        return jsonify({'error': 'Message is required'}), 400

    # Use session ID to identify the user
    sid = session.get('_id')
    if not sid:
        sid = str(uuid.uuid4())
        session['_id'] = sid

    # ---- Name detection ----
    name = is_name_intro(user_message)
    if name:
        save_memory(sid, 'userName', name)

    # ---- 1. Active workflow? ----
    if is_workflow_active(sid):
        result = advance_workflow(sid, user_message)
        if result and result.get('done'):
            wf_type = result['type']
            answers = result['answers']
            if wf_type == 'DAILY_DIG' and answers.get('objective'):
                save_memory(sid, 'mainObjective', answers['objective'])
                save_memory(sid, 'mainObjectiveStatus', 'in-progress')

            # Build a synthesis prompt for the AI
            if wf_type == 'DAILY_DIG':
                prompt = (f"The user's Main Objective is: \"{answers.get('objective')}\". "
                          f"Obstacle: \"{answers.get('obstacle')}\". "
                          f"As the Arboreal Sage, suggest ONE small, concrete 'Seed' — a single action — they can plant today. "
                          f"Respond in 2-3 sentences with nature metaphors.")
            else:  # REFLECTION
                prompt = (f"User's Challenge: \"{answers.get('challenge')}\". "
                          f"Sunlight found: \"{answers.get('sunlight')}\". "
                          f"As the Arboreal Sage, offer ONE 'Growth Point' — a short, actionable insight. "
                          f"Respond in 2-3 sentences with nature metaphors.")

            ai_reply = ai_service.generate_response(prompt, get_all_memories(sid), None)
            summary = generate_workflow_summary(wf_type, answers)
            full_reply = f"{summary}\n\n{ai_reply}"
            clear_workflow(sid)
            return jsonify({'reply': full_reply})

        elif result and not result.get('done'):
            return jsonify({'reply': result['prompt']})
        else:
            clear_workflow(sid)
            return jsonify({'reply': "Let's start over. What would you like to do?"})

    # ---- 2. Workflow start intent ----
    wf_intent = detect_workflow_intent(user_message)
    if wf_intent:
        prompt = start_workflow(sid, wf_intent)
        if prompt:
            return jsonify({'reply': f"🌱 Let's begin {WORKFLOWS[wf_intent]['name']}. {prompt}"})
        else:
            return jsonify({'reply': "I couldn't start that workflow. Please try again."})

    # ---- 3. Memory recall intent ----
    if is_memory_check(user_message):
        obj = get_memory(sid, 'mainObjective')
        if obj:
            prompt = f"The user is asking about their Main Objective: \"{obj}\". Warmly ask how it's taking root, in 1-2 nature-metaphored sentences."
            reply = ai_service.generate_response(prompt, get_all_memories(sid), None)
            return jsonify({'reply': reply})
        else:
            return jsonify({'reply': "You haven't set a root objective yet. Would you like to start a Daily Dig?"})

    # ---- 4. Free chat ----
    wf_context = None
    state = get_workflow(sid)
    if state and state.get('is_active'):
        wf_context = {'type': state['type'], 'prompt': get_current_prompt(sid)}

    memories = get_all_memories(sid)
    reply = ai_service.generate_response(user_message, memories, wf_context)
    return jsonify({'reply': reply})

# ============================================================
# 6. Health check
# ============================================================
@app.route('/api/health', methods=['GET'])
def health():
    return jsonify({'status': '🌱 The Arboreal Sage is awake'})

# ============================================================
# 7. Serve frontend directly from root (FIXED encoding)
# ============================================================
@app.route('/')
def serve_frontend():
    # Open with UTF-8 encoding to avoid UnicodeDecodeError
    return open('frontend.html', encoding='utf-8').read()

@app.route('/<path:path>')
def static_files(path):
    # If you have additional static assets (CSS, images), you'd serve them here.
    # For now, return 404 for any other request.
    return "Not found", 404

# ============================================================
# 8. Run the app
# ============================================================
if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=True)